site_name: Daz University

nav:
  - Home: 'index.md'
  - Content Creation Basics:
      - Installing Daz Studio: 'setup/installing_studio.md'
      - Installing Content: 'setup/content_install.md'
      - Customizing Studio: 'setup/layout.md'
      - Custom Scripts: 'setup/custom_scripts.md'
  - Tools:
      - Mesh Tools:
        - Morph Loader Pro: 'tools/morph_loader_pro.md'
        - Transfer Utility: 'tools/transfer_utility.md'
  - Characters:
      - What is a Daz Character?: 'character_creation/character_creation_first_steps.md'
      - Character Types:
        - Spin Dial Characters: 'character_creation/spin_dial_character.md'
        - Character Modeling: 'character_creation/character_modeling.md'
        - HD Character Sculpting: 'character_creation/hd_character.md'
      - Genesis 9:
        - Key Points: 'character_creation/character_creation_key_points.md'
        - G9 Sculpting Cheat Sheet: 'character_creation/g9_sculpting_cheat_sheet.md'
        - G9 Sculpting Workflow: 'character_creation/g9_dos_and_donts.md'
        - Character Rigging in Daz Studio: 'character_creation/what_is_character_rigging.md'
        - Developer Kit: 'character_creation/G9_dev_kit.md'
  - Poses and Animations:
      - Poses: 'poses/poses.md'
      - Expressions: 'poses/expressions.md'
      - Pose Presets: 'poses/animations.md'
      - Animations: 'poses/animations.md'
  - Props and Environments:
      - Environments: 'props/environments.md'
      - Hand Props: 'props/hand_props.md'
      - Daz to GLTF using Blender: 'extra/gltf_conversion.md'
  - Clothing:
      - Clothing Creation Principles: 'clothing_creation/clothing_general_guidelines.md'
      - Clothing Reference Videos: 'clothing_creation/clothing_reference_videos.md'
      - 00 | Clothing Creation Basics: 'clothing_creation/mada_basics.md'
      - 01 | Flat Sandals: 'clothing_creation/flat_sandals.md'
      - 02 | Tight Top: 'clothing_creation/tight_top.md'
      - 03 | Buttons with Rigid Follow: 'clothing_creation/rigid_follow_buttons.md'
      - 04 | Long Pants: 'clothing_creation/long_pants.md'
      - 05 | Long Sleeve Shirt: 'clothing_creation/long_sleeve_shirt.md'
      - 06 | Finished Product Organization: 'clothing_creation/finished_product_organization.md'
      - 07 | Glasses and Rigidity Maps: 'clothing_creation/glasses_rigidity_maps.md'
      - 08 | Floor Length Dress with Control Bones: 'clothing_creation/floor_length_dress.md'
      - 09 | High Heels: 'clothing_creation/high_heels.md'
      - TIP | Fix Geometry after Rigging: 'clothing_creation/fix_geometry_after_rigging.md'
      - TIP | Split Geometry on a Finished Outfit: 'clothing_creation/split_geometry.md'
  - Hair:
      - Hair: 'hair/hair.md'
  - Product Submission:
      - New Published Artists: 'product_submission/New_PA_Welcome.md'
      - Selling with Daz: 'product_submission/SellingWithDaz.md'
      - Promotional Artwork Guidelines: 'product_submission/promo_artwork_standards.md'
      - Published Artist Support:
          - Checking a Character: 'pa_support/checking_a_character.md'
  - Webinars:
      - Webinars: 'webinars/about_webinars.md'
      - 01 - Morph Loader Pro and Corrective Morphs: 'webinars/webinar_1.md'
      - 02 - Character Presets, Layouts, Weight Painting: 'webinars/webinar_2.md'
      - 03 - Geografting, HD Morphs, and Transfer Utility: 'webinars/webinar_3.md'
      - 04 - Scripting in Daz Studio and Shading Questions: 'webinars/webinar_4.md'
      - 05 - dForce clothing simulations: 'webinars/webinar_5.md'
      - 06 - Rigging Hair and Clothes: 'webinars/webinar_6.md'
      - 07 - HDRIs and clothing fixes: 'webinars/webinar_7.md'
      - 08 - Clothing rigging basics: 'webinars/webinar_8.md'
      - 09 - Rigidity and bone followers: 'webinars/webinar_9.md'
      - 10 - Rigging a long dress and dForce: 'webinars/webinar_10.md'
      - 11 - dForce settings: 'webinars/webinar_11.md'
      - 12 - dForce settings: 'webinars/webinar_12.md'
      - 13 - High heel rigging: 'webinars/webinar_13.md'
      - 14 - Shader Mixer: 'webinars/webinar_14.md'
      - 15 - Shader Mixer and dForce dynamic surface add-on: 'webinars/webinar_15.md'
      - 16 - dForce seams and simulation: 'webinars/webinar_16.md'
      - 17 - dForce and clothing rigging: 'webinars/webinar_17.md'
      - 18 - Iray, Conditional Grafts, Wearable presets: 'webinars/webinar_18.md'
      - 19 - Viewport tips: 'webinars/webinar_19.md'
      - 20 - Bone orientation and iray transmission settings: 'webinars/webinar_20.md'
      - 21 - Iray lighting and canvases: 'webinars/webinar_21.md'
      - 22 - iray, sample scripts and dForce animation: 'webinars/webinar_22.md'
      - 23 - Keyed ERC, MCM/JCM tips, dForce setting updates: 'webinars/webinar_23.md'
      - 24 - Prop scale, character scale, donor figures: 'webinars/webinar_24.md'
      - 25 - Weight maps, finding content, point at: 'webinars/webinar_25.md'
      - 26 - weightmapping genesis 2 and layered image editor: 'webinars/webinar_26.md'
      - 27 - transferring morphs from G8 to G3, rigging a skirt: 'webinars/webinar_27.md'
      - 28 - Character building Q&A: 'webinars/webinar_28.md'
      - 29 - ERC and additive character morphs: 'webinars/webinar_29.md'
      - 30 - Managing content, submitting a bundle, saving poses: 'webinars/webinar_30.md'
      - 31 - Geografting a tail and rigging a belt buckle: 'webinars/webinar_31.md'
      - 32 - Customizing Daz Studio, Character Q&A: 'webinars/webinar_32.md'
      - 33 - Pre-release files and promo requirements: 'webinars/webinar_33.md'
      - 34 - Clothing JCMs and dForce settings: 'webinars/webinar_34.md'
      - 35 - QA standards, naming, and testing: 'webinars/webinar_35.md'
      - 36 - Part 1 Product approval process: 'webinars/webinar_36.md'
      - 36 - Part 2 Cleaning up morphs: 'webinars/webinar_37.md'
      - 37 - Iray skin settings and rigging attachments: 'webinars/webinar_38.md'
      - 38 - Animation and character rigging: 'webinars/webinar_39.md'
      - 39 - Character creation: 'webinars/webinar_40.md'
      - 40 - Rigidity, rigid-follow nodes, and control bones: 'webinars/webinar_41.md'
      - 41 - Basic rigging concepts, hand props, and nodes: 'webinars/webinar_42.md'
      - 42 - dForce fur and hair (outdated): 'webinars/webinar_43.md'
      - 43 - Guest Lyoness, hair, wind, clothing: 'webinars/webinar_44.md'
      - 44 - Guest Dimension Theory on render canvases: 'webinars/webinar_45.md'
      - 45 - Multidimensional Property Script, prop scale, dForce hair: 'webinars/webinar_46.md'
      - 45 - Iray Uber shader settings: 'webinars/webinar_47.md'
      - 47 - Figure morph settings and controls: 'webinars/webinar_48.md'
      - 49 - Character morphs and presets, instances, double sided iray shader: 'webinars/webinar_49.md'
      - 50 - Silent OBJ export script, animation script samples, PASS update: 'webinars/webinar_50.md'
      - 51 - Shrinking product sizes: 'webinars/webinar_51.md'
      - 52 - UV mapping requirements and texture sizes: 'webinars/webinar_52.md'
      - 53 - Promotional renders, image noise removal, curly dForce hair: 'webinars/webinar_53.md'
      - 54 - dForce hair process (automated with new tool): 'webinars/webinar_54.md'
      - 55 - dForce hair pipeline: 'webinars/webinar_55.md'
      - 56 - Shoe creation: 'webinars/webinar_56.md'
      - 57 - Saving templates and hierarchical presets: 'webinars/webinar_57.md'
      - 58 - dForce hair process update: 'webinars/webinar_58.md'
      - 59 - Update base geometry, Transfer Utility, material preset conversion: 'webinars/webinar_59.md'
      - 60 - Smoothing modifier, weight mapping morphs influence, projection morphs: 'webinars/webinar_60.md'
      - 61 - Pose controls, hiding and fitting feet in shoes, twist bones: 'webinars/webinar_61.md'
      - 62 - Strand Based hair with Garibaldi: 'webinars/webinar_62.md'
      - 63 - dForce hair creation and updates: 'webinars/webinar_63.md'
      - 64 - Mesh resolution and creating strand based hair: 'webinars/webinar_64.md'


theme:
  name: material
  favicon: img/favicon.ico
  logo: img/daz-logo-main.webp
  features:
    - navigation.tabs
    - search.suggest
    - search.highlight
    - search.share
  palette:
    - scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - scheme: default
      primary: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode



      # primary: light blue
    # scheme: slate

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - mkdocs-video
  - search
  - exclude-search:
      exclude:
        webinar_1.md#video
        webinar_2.md#video
        webinar_3.md#video
        webinar_4.md#video
        webinar_5.md#video
        webinar_6.md#video
        webinar_7.md#video
        webinar_8.md#video
        webinar_9.md#video
        webinar_10.md#video
        webinar_11.md#video
        webinar_12.md#video
        webinar_13.md#video
        webinar_14.md#video
        webinar_15.md#video
        webinar_16.md#video
        webinar_17.md#video
        webinar_18.md#video
        webinar_19.md#video
        webinar_20.md#video
        webinar_21.md#video
        webinar_22.md#video
        webinar_23.md#video
        webinar_24.md#video
        webinar_25.md#video
        webinar_26.md#video
        webinar_27.md#video
        webinar_28.md#video
        webinar_29.md#video
        webinar_30.md#video
        webinar_31.md#video
        webinar_32.md#video
        webinar_33.md#video
        webinar_34.md#video
        webinar_35.md#video
        webinar_36.md#video
        webinar_37.md#video
        webinar_38.md#video
        webinar_39.md#video
        webinar_40.md#video
        webinar_41.md#video
        webinar_42.md#video
        webinar_43.md#video
        webinar_44.md#video
        webinar_45.md#video
        webinar_46.md#video
        webinar_47.md#video
        webinar_48.md#video
        webinar_49.md#video
        webinar_50.md#video
        webinar_51.md#video
        webinar_52.md#video
        webinar_53.md#video
        webinar_54.md#video
        webinar_55.md#video
        webinar_56.md#video
        webinar_57.md#video
        webinar_58.md#video
        webinar_59.md#video
        webinar_60.md#video
        webinar_61.md#video
        webinar_62.md#video
        webinar_63.md#video
        webinar_64.md#video
  - offline
#  - print-site

