site_name: Daz University

nav:
  - Home: 'index.md'
  - Content Creation Setup:
      - Installations:
        - Installing Daz Studio: 'setup/installing_studio.md'
      - Customizing Studio: 'setup/layout.md'
      - Custom Scripts: 'setup/custom_scripts.md'
      - Installing Content: 'setup/content_install.md'
  - Tools:
      - Mesh Tools:
        - Morph Loader Pro: 'tools/morph_loader_pro.md'
        - Transfer Utility: 'tools/transfer_utility.md'
  - Characters:
      - What is a Daz Character?: 'character_creation/character_creation_first_steps.md'
      - Character Types:
        - Spin Dial Characters: 'character_creation/spin_dial_character.md'
        - Character Modeling: 'character_creation/character_modeling.md'
        - HD Character Sculpting: 'character_creation/hd_character.md'
      - Poses:
          - Saving Poses: 'character_creation/pose.md'
  - Clothing:
      - High Heels: 'clothing_creation/high_heels.md'
  - Product Submission:
      - Promotional Artwork Guidelines: 'product_submission/promo_artwork_standards.md'
  - File Conversions:
      - Daz to GLTF using Blender: 'extra/gltf_conversion.md'
  - Webinars:
      - 01 - Morph Loader Pro and Corrective Morphs: 'webinars/August 29, 2017.md'
      - 02 Character Presets, Layouts, Weight Painting: 'webinars/August 31, 2017.md'
      - 04 Geografting, HD Morphs, and Transfer Utility: 'webinars/September 6, 2017.md'
      - 04 Scripting in Daz Studio and Shading Questions: 'webinars/September 8, 2017.md'
      - dForce clothing simulations: 'webinars/September 12, 2017.md'
      - 06 Rigging Hair and Clothes: 'webinars/September 14, 2017.md'
      - 07 HDRIs and clothing fixes: 'webinars/September 19, 2017.md'
      - 08 Clothing rigging basics: 'webinars/September 21, 2017.md'
      - 09 Rigidity and bone followers: 'webinars/September 26, 2017.md'
      - 10 Rigging a long dress and dForce: 'webinars/September 28, 2017.md'
      - 11 dForce settings: 'webinars/October 3, 2017.md'
      - 12 dForce settings: 'webinars/October 6, 2017.md'
      - 13 High heel rigging: 'webinars/October 10, 2017.md'
      - 14 Shader Mixer: 'webinars/October 12, 2017.md'
      - 15 Shader Mixer and dForce dynamic surface add-on: 'webinars/October 18, 2017.md'
      - 16 dForce seams and simulation: 'webinars/October 24, 2017.md'
      - 17 dForce and clothing rigging: 'webinars/October 26, 2017.md'
      - 18 Iray, Conditional Grafts, Wearable presets: 'webinars/October 31, 2017.md'
      - 19 Viewport tips: 'webinars/November 2, 2017.md'
      - 20 Bone orientation and iray transmission settings: 'webinars/November 7, 2017.md'
      - 21 Iray lighting and canvases: 'webinars/November 9, 2017.md'
      - 22 iray, sample scripts and dForce animation: 'webinars/November 14, 2017.md'
      - 23 Keyed ERC, MCM/JCM tips, dForce setting updates: 'webinars/November 16, 2017.md'
      - 24 Prop scale, character scale, donor figures: 'webinars/November 21, 2017.md'
      - 25 Weight maps, finding content, point at: 'webinars/November 28, 2017.md'
      - 26 weightmapping genesis 2 and layered image editor: 'webinars/November 30, 2017.md'
      - 27 transferring morphs from G8 to G3, rigging a skirt: 'webinars/December 7, 2017.md'
      - 28 Character building Q&A: 'webinars/December 14, 2017.md'
      - 29 ERC and additive character morphs: 'webinars/December 21, 2017.md'
      - 30 Managing content, submitting a bundle, saving poses: 'webinars/January 12, 2018.md'
      - 31 Geografting a tail and rigging a belt buckle: 'webinars/January 18, 2018.md'
      - 32 Customizing Daz Studio, Character Q&A: 'webinars/January 25, 2018.md'
      - 33 Pre-release files and promo requirements: 'webinars/February 1, 2018.md'
      - 34 Clothing JCMs and dForce settings: 'webinars/February 8, 2018.md'
      - 35 QA standards, naming, and testing: 'webinars/Feburary 15, 2018.md'
      - 36 - Part 1 Product approval process: 'webinars/March 1, 2018 Part 1.md'
      - 36 - Part 2 Cleaning up morphs: 'webinars/March 1, 2018 Part 2.md'
      - 37 iray skin settings and rigging attachments: 'webinars/March 8, 2018.md'
      - 38 Animation and character rigging: 'webinars/March 15, 2018.md'
      - 39 Character creation: 'webinars/March 22, 2018.md'
      - 40 Rigidity, rigid-follow nodes, and control bones: 'webinars/March 29, 2018.md'
      - 41 Basic rigging concepts, hand props, and nodes: 'webinars/April 5, 2018.md'
      - 42 dForce fur and hair (outdated): 'webinars/April 26, 2018.md'
      - 43 Guest Speaker Lyoness, hair, wind, clothing: 'webinars/May 3, 2018.md'
      - 44 Guest speaker Dimension Theory on render canvases: 'webinars/May 10, 2018.md'
      - 45 Multidimensional Property Script, prop scale, dForce hair: 'webinars/May 17, 2018.md'
      - 45 Iray Uber shader settings: 'webinars/May 24, 2018.md'
      - 47 Figure morph settings and controls: 'webinars/May 31, 2018.md'
      - 49 Character morphs and presets, instances, double sided iray shader: 'webinars/June 14, 2018.md'
      - 50 Silent OBJ export script, animation script samples, PASS update: 'webinars/June 21, 2018.md'
      - 51 Shrinking product sizes: 'webinars/June 28, 2018.md'
      - 52 UV mapping requirements and texture sizes: 'webinars/July 19, 2018.md'
      - 53 Promotional renders, image noise removal, curly dForce hair: 'webinars/July 26, 2018.md'
      - 54 dForce hair process (automated with new tool): 'webinars/August 2, 2018.md'
      - 55 dForce hair pipeline: 'webinars/August 16, 2018.md'
      - 56 Shoe creation: 'webinars/August 30, 2018.md'
      - 57 Saving templates and hierarchical presets: 'webinars/September 20, 2018.md'
      - 58 dForce hair process update: 'webinars/November 15, 2018.md'
      - 59 Update base geometry, Transfer Utility, material preset conversion: 'webinars/November 29, 2018.md'
      - 60 Smoothing modifier, weight mapping morphs influence, projection morphs: 'webinars/December 13, 2018.md'
      - 61 Pose controls, hiding and fitting feet in shoes, twist bones: 'webinars/January 10, 2019.md'
      - 62 Strand Based hair with Garibaldi: 'webinars/January 24, 2019.md'
      - 63 dForce hair creation and updates: 'webinars/February 8, 2019.md'
      - 64 Mesh resolution and creating strand based hair: 'webinars/February 22, 2019.md'
      - Webinar 01 - 29 August 2017: 'webinars/webinar_001-08-08-2017.md'

theme:
  name: material
  features:
    - navigation.tabs
  theme:
    palette:
      primary: light blue
#      - scheme: default
#        toggle:
#          icon: material/toggle-switch-off-outline
#          name: Switch to dark mode
#      - scheme: slate
#        toggle:
#          icon: material/toggle-switch
#          name: Switch to light mode


      # primary: light blue
    # scheme: slate

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - mkdocs-video
  - search
  - exclude-search
